
- name: CentOS 7 | Check needs-restarting
  shell: /bin/needs-restarting -r
  register: needs_restarting
  ignore_errors: True
  failed_when: False
  changed_when: False
  when: ( ansible_local is defined and ansible_local.ova is not defined )

## 776 : /sbin/dhclient
#- name: "Debug the needs_restarting output"
#  debug:
#    msg: "{{ needs_restarting }}\n {{ needs_restarting.stdout.find('/') }}\n {{ needs_restarting.stdout | search('[0-9]* : /.*') }}"

- name: CentOS 7 | Set reboot action on nodes that need restarting
  debug:
    msg: "Node flagged for reboot by package manager"
  when:
    - ( needs_restarting|failed ) and flag_install_node is not defined
    - not ( ansible_local is defined and ansible_local.ova is defined )

- name: CentOS 7 | Check if install node also needs restarting
  debug:
    msg: "The install node also needs restarting, but we can't reboot right now."
  notify:
    - CentOS 7 | Reboot required
  when:
    - ( needs_restarting|failed ) and flag_install_node is defined
    - not ( ansible_local is defined and ansible_local.ova is defined )

- name: CentOS 7 | Reboot node(s)
  become: True
  shell: sleep 5 && /sbin/shutdown -r now "Node flagged for reboot by package manager"
  async: 1
  poll: 0
  ignore_errors: True
  when:
    - ( needs_restarting|failed ) and flag_install_node is not defined
    - not ( ansible_local is defined and ansible_local.ova is defined )

- name: CentOS 7 | Wait for node(s) to reboot
  become: False
  local_action: wait_for host="{{ ansible_host | default(inventory_hostname) }}" port="{{ ansible_port }}" state=started delay=15 timeout=300
  when:
    - ( needs_restarting|failed ) and flag_install_node is not defined
    - not ( ansible_local is defined and ansible_local.ova is defined )

  # host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=120

#- name: CentOS 7 | Reboot node
#  shell: sleep 5 && shutdown -r now "Node flagged for reboot by package manager"
#  become: yes
#  async: 1
#  poll: 0
#  ignore_errors: True
#  failed_when: False
#  changed_when: ( needs_restarting|failed ) and flag_install_node is not defined
#
#- name: CentOS 7 | Wait for node to reboot
#  wait_for:
#    port: 22
#    host: "{{ ansible_host | default(inventory_hostname) }}"
#    delay: 10
#    connect_timeout: 10
#    timeout: 300
#    state: started
#  delegate_to: "{{ groups['install_node'][0] }}"
