- include_vars: caches.yml

- name: Selinux | Set selinux permissive
  selinux: policy=targeted state=permissive

- name: Common | Build cache paths
  vars:
    become: true
  file:
    state: directory
    path: "{{host_cache_dir}}/{{ item }}"
  with_items: "{{ caches }}"
  when: flag_install_node is not defined
  tags: files

# This could be faster with synchronize (rsync) but
- name: Common | Sync caches to nodes
  vars:
    become: true
  copy:
    src: "{{cache_dir}}/{{item.key}}/"
    dest: "{{host_cache_dir}}/{{item.key}}/"
  when: ( item.value.applies_to in group_names ) and ( flag_install_node is not defined )"
  with_dict: "{{ caches }}"
