---
type: map
mapping:

  licensing:
    type: map
    required: False
    mapping:
      license_accepted:
        type: bool

  autonames:
    type: map
    required: False
    mapping:
      custom:
        type: seq
        required: True
        sequence:
          - type: str
            required: True
            func: valid_hostname

  facts:
    type: map
    required: True
    mapping:
      install_node:
        type: str
        required: True
        func: ipv4_address

      management_clients:
        type: seq
        required: True
        sequence:
          - type: str
            func: ipv4_cidr

      ssh_defaults:
        type: map
        required: True
        mapping:
          ssh_username:
            type: str
            func: alphanumeric
            required: True
          ssh_password:
            type: str
            required: True
          ssh_port:
            type: int
            required: False
          ansible_user:
            type: str
            func: alphanumeric
            required: False
          ansible_ssh_pass:
            type: str
            required: False
          ansible_become_pass:
            type: str
            required: False
          ssh_private_key:
            type: str
            required: False
          ssh_public_key:
            type: str
            required: False
          ssh_crypto:
            type: str
            func: valid_crypto_method
            required: False

      node_defaults:
        type: map
        required: True
        mapping:
          entropy_source:
            type: str
            func: unix_path
            required: False
          autonaming:
            type: str
            required: False
          ecs_root_user:
            type: str
            func: alphanumeric
            required: False
          ecs_root_pass:
            type: str
            required: False
          dns_domain:
            type: str
            required: True
          dns_servers:
            type: seq
            required: True
            sequence:
              - type: str
          ntp_servers:
            type: seq
            required: True
            sequence:
              - type: str

      storage_pool_defaults:
        type: map
        required: False
        mapping:
          is_cold_storage_enabled:
            type: bool
            required: False
          is_protected:
            type: bool
            required: False
          description:
            type: str
            required: False
          ecs_block_devices:
            type: seq
            required: False
            sequence:
              - type: str
                func: unix_path

      storage_pools:
        type: seq
        required: True
        sequence:
          - type: map
            mapping:
              name:
                type: str
                func: alphanumeric
                required: True
              members:
                type: seq
                required: True
                sequence:
                  - type: str
                    func: ipv4_address
              options:
                type: map
                required: True
                mapping:
                  is_cold_storage_enabled:
                    type: bool
                    required: False
                  is_protected:
                    type: bool
                    required: False
                  description:
                    type: str
                    required: False
                  ecs_block_devices:
                    required: True
                    type: seq
                    sequence:
                      - type: str
                        func: unix_path

      virtual_data_center_defaults:
        type: map
        required: False
        mapping:
          description:
            type: str
            required: False

      virtual_data_centers:
        type: seq
        required: True
        sequence:
          - type: map
            mapping:
              name:
                type: str
                func: alphanumeric
                required: True
              members:
                type: seq
                required: True
                sequence:
                  - type: str
                    func: alphanumeric
              options:
                type: map
                required: False
                mapping:
                  description:
                    type: str
                    required: False

      replication_group_defaults:
        type: map
        required: False
        mapping:
          description:
            type: str
            required: False
          enable_rebalancing:
            type: bool
            required: False
          allow_all_namespaces:
            type: bool
            required: False
          is_full_rep:
            type: bool
            required: False

      replication_groups:
        type: seq
        required: False
        sequence:
          - type: map
            mapping:
              name:
                type: str
                func: alphanumeric
                required: True
              members:
                type: seq
                required: True
                sequence:
                  - type: str
                    func: alphanumeric
              options:
                type: map
                required: False
                mapping:
                  description:
                    type: str
                    required: False
                  enable_rebalancing:
                    type: bool
                    required: False
                  allow_all_namespaces:
                    type: bool
                    required: False
                  is_full_rep:
                    type: bool
                    required: False

      namespace_defaults:
        type: map
        required: False
        mapping:
          is_stale_allowed:
            required: False
            type: bool
          is_compliance_enabled:
            required: False
            type: bool
          is_encryption_enabled:
            required: False
            type: bool

      namespaces:
        type: seq
        required: False
        sequence:
          - type: map
            mapping:
              name:
                type: str
                func: alphanumeric
                required: True
              administrators:
                type: seq
                required: True
                sequence:
                  - type: str
                    func: alphanumeric
              replication_group:
                type: str
                func: alphanumeric
                required: True
              options:
                type: map
                required: False
                mapping:
                  is_stale_allowed:
                    type: bool
                    required: False
                  is_compliance_enabled:
                    type: bool
                    required: False
                  is_encryption_enabled:
                    type: bool
                    required: False

      management_user_defaults:
        type: map
        required: False
        mapping:
          is_system_admin:
            type: bool
            required: False
          is_system_monitor:
            type: bool
            required: False

      management_users:
        type: seq
        required: False
        sequence:
          - type: map
            mapping:
              username:
                type: str
                func: alphanumeric
                required: True
              password:
                type: str
                required: True
              options:
                type: map
                required: False
                mapping:
                  is_system_admin:
                    type: bool
                    required: False
                  is_system_monitor:
                    type: bool
                    required: False

      object_user_defaults:
        type: map
        required: False
        mapping:
          swift_password:
            type: str
            func: alphanumeric
            required: False
          swift_groups_list:
            type: seq
            required: False
            sequence:
              - type: str
                required: True
                func: alphanumeric
          s3_expiry_time:
            type: int
            required: False
          s3_secret_key:
            type: str
            func: s3_secret_key
            required: False

      object_users:
        type: seq
        required: False
        sequence:
          - type: map
            mapping:
              username:
                type: str
                func: alphanumeric
                required: True
              namespace:
                type: str
                func: alphanumeric
                required: True
              options:
                type: map
                required: False
                mapping:
                  swift_password:
                    type: str
                    func: alphanumeric
                    required: False
                  swift_groups_list:
                    type: seq
                    required: False
                    sequence:
                      - type: str
                        required: True
                        func: alphanumeric
                  s3_expiry_time:
                    type: int
                    required: False
                  s3_secret_key:
                    type: str
                    func: s3_secret_key
                    required: False

      object_user_defaults:
        type: map
        required: False
        mapping:
          swift_password:
            type: str
            func: alphanumeric
            required: False
          swift_groups_list:
            type: seq
            required: False
            sequence:
              - type: str
                required: True
                func: alphanumeric
          s3_expiry_time:
            type: int
            required: False
          s3_secret_key:
            type: str
            func: s3_secret_key
            required: False

      # [Optional]
      # Bucket layout (optional)
      buckets:
        type: seq
        required: False
        sequence:
          - type: map
            required: True
            mapping:
              name:
                type: str
                func: alphanumeric
                required: True
              options:
                type: map
                required: True
                mapping:
                  namespace:
                    type: str
                    func: alphanumeric
                    required: False
                  replication_group:
                    type: str
                    func: alphanumeric
                    required: False
                  owner:
                    type: str
                    func: alphanumeric
                    required: False
                  head_type:
                    type: str
                    func: alphanumeric
                    required: True
                  filesystem_enabled:
                    type: bool
                    required: False
                  stale_allowed:
                    type: bool
                    required: False
                  encryption_enabled:
                    type: bool
                    required: False

      # [Optional]
      # Bucket defaults
      bucket_defaults:
        type: map
        required: False
        mapping:
          namespace:
            type: str
            func: alphanumeric
            required: True
          replication_group:
            type: str
            func: alphanumeric
            required: True
          head_type:
            type: str
            func: alphanumeric
            required: False
          filesystem_enabled:
            type: bool
            required: False
          stale_allowed:
            type: bool
            required: False
          encryption_enabled:
            type: bool
            required: False
          owner:
            type: str
            func: alphanumeric
            required: False
