- include_vars: main.yml

- name: Installer | Check RSA Keypair
  stat: path="{{keys_rsa.priv_key}}"
  register: rsa_keypair

- name: Installer | Generate RSA Keypair
  command: "{{keys_rsa.keygen_cmd}} {{keys_rsa.priv_key}}"
  when: not rsa_keypair.stat.exists

- name: Installer | Check ed25519 Keypair
  stat: path="{{keys_ed25519.priv_key}}"
  register: ed25519_keypair

- name: Installer | Generate ed25519 Keypair
  command: "{{keys_ed25519.keygen_cmd}} {{keys_ed25519.priv_key}}"
  when: not ed25519_keypair.stat.exists

- name: Installer | Ensure directory permissions on ssh keystore
  file:
    path: "{{item.key}}"
    state: "{{item.value.state}}"
    mode: "{{item.value.mode}}"
    owner: "{{item.value.owner}}"
    group: "{{item.value.group}}"
  with_dict: "{{ssh_dir_paths}}"
