- name: Common | Ping data nodes before doing anything else
  hosts: data_node
  gather_facts: false
  tasks:
    - ping: "{{inventory_hostname}}"

- name: Common | Start and enable ECS services
  hosts: data_node
  roles:
    - common_start_enable_service
#    - common_run_cf_client
