- name: Installer | Build the package cache
  hosts: ecs_install
  roles:
    - installer_build_cache

- name: Installer | Enable torrent ffx
  hosts: ecs_install
  tasks:
    - file:
        path: "{{ffx_sem}}"
        state: touch
