- include_vars: main.yml
- include_vars: caches.yml

- name: Common | Create and modify paths and semaphores for docker containers
  file:
    path: "{{item.path}}"
    state: "{{item.state}}"
    mode: "{{item.mode}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items: "{{ecs_docker_dirs}}"
  tags: files
  loop_control:
    label: "{{item.path}}"

### Generate network.json
- name: Common | Generate network.json
  template: src=rev1-network.json.j2 dest=/host/data/network.json owner=444 group=444 force=no
  tags: files

### Generate object-main_network.json
- name: Common | Generate object-main_network.json
  template: src=object-main_network.json.j2 dest=/host/data/object-main_network.json owner=444 group=444 force=no
  tags: files

### Generate id.json
- name: Common | Generate id.json
  template: src=id.json.j2 dest=/host/data/id.json owner=444 group=444 force=no
  tags: files

### Generate agent.json
- name: Common | Generate agent.json
  template: src=agent.json.j2 dest=/host/data/agent.json owner=444 group=444 force=no
  tags: files

### Generate seeds file
- name: Common | Generate seeds file
  template: src=seeds.j2 dest=/host/files/seeds owner=444 group=444 force=no
  tags: files
