- include_vars: caches.yml

- name: Debug
  debug:
    msg: "data nodes: {{num_data_nodes|int}} top data node: {{top_data_node}} install node: {{groups['install_node'][0]}} is ova?: {{ansible_local is defined and ansible_local.ova is defined}}"

- name: Debug 2
  debug:
    msg: "{{not ( num_data_nodes|int == 1 and top_data_node == groups['install_node'][0] )}}"

- name: Debug 3
  debug:
    msg: "{{not ( ansible_local is defined and ansible_local.ova is defined )}}"

- name: Debug 4
  debug:
    msg: "ansible_local: {{ansible_local is defined}} ansible_local.ova: {{ansible_local is defined and ansible_local.ova is defined}}"

- name: Installer | Create cache directories
  file: state=directory path={{ cache_dir }}/{{ item }}
  with_items: "{{ caches }}"
  when:
    - not ( num_data_nodes|int == 1 and top_data_node == groups['install_node'][0] )
    - not ( ansible_local is defined and ansible_local.ova is defined )
  loop_control:
    label: "{{ cache_dir }}/{{ item }}"

- name: Installer | Create compressed cache files
  shell: "{{ item.value.pack_cmd }}"
  args:
    chdir: "{{ host_cache_dir }}/{{ item.key }}"
    creates: "{{ host_cache_dir }}/{{ item.key }}/{{ item.value.dest }}"
  with_dict: "{{ caches }}"
  delegate_to: "{{ groups['install_node'][0] }}"
  register: cacheresults
  when:
    - not ( num_data_nodes|int == 1 and top_data_node == groups['install_node'][0] )
    - not ( ansible_local is defined and ansible_local.ova is defined )
  loop_control:
    label: "{{ host_cache_dir }}/{{ item.key }}/{{ item.value.dest }}"

- name: Installer | Create cache distribution torrent file
  shell: /usr/bin/mktorrent-borg -ig 'facts*' -a udp://{{ groups['install_node'][0] }}:6881 -a http://{{ groups['install_node'][0] }}:6881/announce -o {{ cache_dir }}/cache.torrent -pub {{ cache_dir }}
  args:
    creates: "{{ cache_dir }}/cache.torrent"
  when:
    - not ( num_data_nodes|int == 1 and top_data_node == groups['install_node'][0] )
    - not ( ansible_local is defined and ansible_local.ova is defined )
