- include_vars: main.yml
- include_vars: caches.yml

### Generate network.json
- name: Common | Generate network.json
  template: src=network-json.j2 dest=/host/data/network.json owner=444 group=444 force=no
  tags: files

### Generate seeds file
- name: Common | Generate seeds file
  template: src=seeds.j2 dest=/host/files/seeds owner=444 group=444 force=no
  tags: files
